#configfile: "config.yaml"
#Will need location of fast5 files, flowcell, kit, ref genome
SAMPLES = ['TEST']
flowcell = 'FLO-MIN106' #Might be a better idea to just provide the config file here instead of the flowcell/kit combo
kit = 'SQK-LSK109'
genomeSize = '2g'

import os

def activate_environment():
    os.system("module load samtools/1.9")
    os.system("module load anaconda3/2019.07")
    os.system("source activate pycoqc")

activate_environment()

rule all:
    input:
        "data/fastq/",
        "data/fastq/sequencing_summary.txt",
        expand("output/{sample}_pycoQC_output.html", sample=SAMPLES),
        expand("output/{sample}.merged.fastq", sample=SAMPLES),
        expand("output/{sample}.merged.fastq.index.gzi", sample=SAMPLES),
        expand("output/{sample}.merged.fastq.index.fai", sample=SAMPLES),
        expand("output/{sample}.merged.fastq.index.readdb", sample=SAMPLES) #,
        #"output/draft/"

#Might need rule here using rsync to move fast5 files from c010 over to /datasets on gpu node

#Change basecall rule to be submitted to GPU cluster, will need to change specs, params, etc.
rule basecall:
    input:
        f5s="data/guppy" #Will need to add in wildcard specification here
    output:
        fqs=directory("data/fastq/"),
        ss="data/fastq/sequencing_summary.txt"
    params:
        jobname="guppy_basecall",
        runtime="48:00",
        memusage="20000",
        slots="20",
        misc=" "
    shell:
        "guppy_basecaller --input_path {input.f5s} --save_path {output.fqs} --flowcell {flowcell} --kit {kit} --num_callers {params.slots}"

#Will need to write rule here to rsync fast5 files back from GPU node to C010 

rule pycoqc:
    input:
        "data/fastq/sequencing_summary.txt"
    output:
        "output/{sample}_pycoQC_output.html"
    params:
        jobname="QC",
        runtime="4:00",
        memusage="10000",
        slots="1",
        misc=" "
    shell:
        "pycoQC -f {input} -o {output}"

rule merge_fastqs:
    input:
        "data/fastq/"
    output:
        "output/{sample}.merged.fastq"
    params:
        jobname="merge_fqs",
        runtime="1:00",
        memusage="5000",
        slots="1",
        misc=" "
    shell:
        "cat {input}/*.fastq > {output}"

rule index:
    input:
        f5s="data/guppy/",
        fq="output/{sample}.merged.fastq"
    output:
        "output/{sample}.merged.fastq.index",
        "output/{sample}.merged.fastq.index.gzi",
        "output/{sample}.merged.fastq.index.fai",
        "output/{sample}.merged.fastq.index.readdb"
    params:
        jobname="index_reads",
        runtime="8:00",
        memusage="5000",
        slots="10",
        misc=" "
    shell:
        "f5c index -d {input.f5s} {input.fq}"

"""

rule compute_draft:
    input:
        fqs=expand("output/{sample}.merged.fastq", sample=SAMPLES) #,
        #prefix=expand("{sample}", sample=SAMPLES)
    output:
        directory("output/draft/")
    params:
        jobname="compute_draft_genome",
        runtime="24:00",
        memusage="20000",
        slots="10",
        misc=" "
    shell:
        "canu -p {SAMPLES} -d {output} genomeSize={genomeSize} -nanopore-raw {input.fqs}"


rule minimap2_align:
    input:
        ref="GCF_000001405.26_GRCh38_genomic.fna",
        fq="data/{sample}.merged.fq"
    output:
        "output/2_mapped/{sample}.sorted.bam"
    params:
        jobname="index_reads",
        runtime="8:00",
        memusage="20000",
        slots="10",
        misc=" "
    shell:
        "minimap2 -t {params.slots} -ax map-ont {input.ref} {input.fq} | samtools sort -o "

rule index_bams:
    input:
        "output/2_mapped/{sample}.sorted.bam"
    output:
        "output/2_mapped/{sample}.sorted.bam.bai"
    params:
        jobname="index_bams",
        runtime="8:00",
        memusage="20000",
        slots="1",
        misc=" "
    shell:
        "samtools index {input}"

rule segment_genome:
    input:
    output:
    params:
        jobname="index_reads",
        runtime="8:00",
        memusage="20000",
        slots="10",
        misc=" "
    shell:
        "python3 /home/k001y/nanopolish/scripts/nanopolish_makerange.py  "

rule concensus:
    input:
    output:
    params:
    shell:

rule vcf2fasta:
    input:
    output:
    params:
        jobname="index_reads",
        runtime="8:00",
        memusage="20000",
        slots="10",
        misc=" "
    shell:
        "/home/k001y/nanopolish/nanopolish vcf2fasta "

rule merge:
    input:
    output:
    params:
    shell:

rule eval_assembly:
    input:
    output:
    params:
        jobname="index_reads",
        runtime="8:00",
        memusage="20000",
        slots="10",
        misc=" "
    shell:

"""