#configfile: "config.yaml"
#samples = config["samples"]
sample = 'FAB39075-4246400039_Multi_SQK-LSK108_WA01'

import os

def activate_environment():
    os.system("module load samtools/1.9")
    os.system("module load anaconda3/2019.07")
    #os.system("source activate /home/k001y/miniconda3/envs/ngmlr-env") #need to change to pycometh env

activate_environment()

rule all:
    input:
        expand("data/{sample}.merged.fq", sample=sample.split(' ')),
        expand("data/{sample}.merged.fq.index", sample=sample.split(' ')),
        expand("data/{sample}.merged.fq.index.gzi", sample=sample.split(' ')),
        expand("data/{sample}.merged.fq.index.fai", sample=sample.split(' ')),
        expand("data/{sample}.merged.fq.index.readdb", sample=sample.split(' ')),
        expand("output/mapped/{sample}.sorted.bam", sample=sample.split(' ')),
        expand("output/mapped/{sample}.sorted.bam.bai", sample=sample.split(' ')),
        expand("output/meth/{sample}.meth_calls.tsv", sample=sample.split(' ')),
        expand("output/meth/{sample}.meth_freq.tsv", sample=sample.split(' '))

rule merge_fastqs:
    input:
        "data/"
    output:
        "data/{sample}.merged.fq"
    params:
        jobname="merged_fqs",
        runtime="1:00",
        memusage="5000",
        slots="1",
        misc=" "
    shell:
        "cat data/{sample}_*.fq > {output}"

#Note that below for the fast5s they are currently just in a folder called guppy. For future work I will need to change this to make it more general

rule index_reads:
    input:
        f5="data/guppy/",
        fq="data/{sample}.merged.fq"
    output:
        "data/{sample}.merged.fq.index",
        "data/{sample}.merged.fq.index.gzi",
        "data/{sample}.merged.fq.index.fai",
        "data/{sample}.merged.fq.index.readdb"
    params:
        jobname="index_reads",
        runtime="8:00",
        memusage="20000",
        slots="10",
        misc=" "
    shell:
        "f5c index -d {input.f5} {input.fq}"

rule ngmlr_align:
    input:
        ref="GCF_000001405.26_GRCh38_genomic.fna",
        fq="data/{sample}.merged.fq"
    output:
        "output/mapped/{sample}.sorted.bam"
    params:
        jobname="index_reads",
        runtime="8:00",
        memusage="20000",
        slots="10",
        misc=" "
    shell:
        "ngmlr -t 10 -r {input.ref} -q {input.fq} -x ont | samtools sort -T tmp -o {output}"

rule index_bams:
    input:
        "output/mapped/{sample}.sorted.bam"
    output:
        "output/mapped/{sample}.sorted.bam.bai"
    params:
        jobname="index_bams",
        runtime="8:00",
        memusage="20000",
        slots="1",
        misc=" "
    shell:
        "samtools index {input}"

rule call_meth:
    input:
        bam="output/mapped/{sample}.sorted.bam",
        bai="output/mapped/{sample}.sorted.bam.bai",
        ref="GCF_000001405.26_GRCh38_genomic.fna",
        fq="data/{sample}.merged.fq",
        index="data/{sample}.merged.fq.index",
        fai="data/{sample}.merged.fq.index.fai",
        gzi="data/{sample}.merged.fq.index.gzi",
        readdb="data/{sample}.merged.fq.index.readdb"
    output:
        "output/meth/{sample}.meth_calls.tsv"
    params:
        jobname="call_meth",
        runtime="24:00",
        memusage="50000",
        slots="10",
        misc=" "
    shell:
        "f5c call-methylation -t 10 -r {input.fq} -b {input.bam} -g {input.ref} > {output}"

rule calc_freq:
    input:
        "output/meth/{sample}.meth_calls.tsv"
    output:
        "output/meth/{sample}.meth_freq.tsv"
    params:
        jobname="calc_freq",
        runtime="8:00",
        memusage="20000",
        slots="1",
        misc=" "
    shell:
        "f5c meth-freq -i {input} -o {output} -s"




