samples: [AS]
index: [/icgc/dkfzlsdf/analysis/C010/brooks/master_pipeline]
ref: [/icgc/dkfzlsdf/analysis/C010/brooks/GCF_000001405.26_GRCh38_genomic.fna]
in_fast5: [/icgc/dkfzlsdf/analysis/C010/brooks/nanopore_raw/GCTB/AS]
in_fastq: [/icgc/dkfzlsdf/analysis/C010/brooks/nanopore_basecalled/GCTB/AS]
out_dir: [/icgc/dkfzlsdf/analysis/C010/brooks/master_pipeline/output/GCTB]